version: '2'

services:
  web:
    build: .
    environment:
      RAILS_ENV: 'production'
    volumes:
      - .:/blog
    command: bin/rails server -p 4242 -b 0.0.0.0
    ports:
      - '4242:4242'
    links:
      - db

  db:
    image: kiasaki/alpine-postgres:9.5
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes_from:
      - db_data

  db_data:
    image: busybox
    volumes:
      - ../db_data/:/var/lib/postgresql/data:rw
