version: '2'

services:
  web:
    build: .
    environment:
      RAILS_ENV: 'production'
    volumes:
      - .:/blog
    volumes_from:
      - public
    command: bin/rails server -p 4242 -b 0.0.0.0
    ports:
      - '4242:4242'
    links:
      - db
      - public

  db:
    image: kiasaki/alpine-postgres:9.5
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes_from:
      - db_data

  public:
    image: busybox
    command: echo 'Serving public'
    volumes:
      - /public

  db_data:
    image: busybox
    volumes:
      - ../db_data/:/var/lib/postgresql/data:rw
