version: '2'

services:
  web:
    build: ./
    image: rails5_web
    volumes:
      - .:/blog
    volumes_from:
      - bundle
    command: bin/rails server -p 4242 -b 0.0.0.0
    ports:
      - '4242:4242'
    links:
      - db
      - bundle

  db:
    image: kiasaki/alpine-postgres
    ports:
      - '5433:5433'
    environment:
      POSTGRES_PASSWORD: 'postgres'



  bundle:
    image: rails5_web
    command: echo 'Serving bundle'
    volumes:
      - /bundle
