version: '2'

services:
  web:
    build: .
    volumes:
      - .:/blog
    volumes_from:
      - bundle
    command: bin/rails server -p 4242 -b 0.0.0.0
    ports:
      - '4242:4242'
    links:
      - db
      - bundle

  db:
    image: kiasaki/alpine-postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw

  bundle:
    image: bovoid/rails5_web
    command: echo 'Serving bundle'
    volumes:
      - /bundle
