- name: Git pull repo
  git:
    repo: '{{ project_repo }}'
    update: yes
    version: master
    dest: '{{ project_home }}'

- name: Docker compose up (restart)
  shell: 'cd {{ project_home }} && docker-compose up -d --build --force-recreate'
